import React, { useState } from "react";
import API from "../services/api";
import { useTheme } from "../context/ThemeContext";
import { useResume } from "../context/ResumeContext";

export default function CoverLetterGenerator() {
  const { theme } = useTheme();
  const { resumeText } = useResume();
  const isDark = theme === "dark";
  const [jobDescription, setJobDescription] = useState("");
  const [coverLetter, setCoverLetter] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const card = isDark ? "bg-[#1a1d27] border-[#2a2e3d] text-white" : "bg-white border-slate-200 text-slate-800";
  const inputClass = isDark ? "bg-white/5 border-white/10 text-white placeholder-slate-500 focus:border-indigo-500" : "bg-slate-50 border-slate-200 text-slate-800 placeholder-slate-400 focus:border-indigo-500";
  const headText = isDark ? "text-white" : "text-slate-800";
  const subText = isDark ? "text-slate-400" : "text-slate-500";

  const generate = async () => {
    if (!jobDescription.trim()) {
      setError("Please paste a Job Description first.");
      return;
    }
    try {
      setIsLoading(true);
      setError(null);
      setCoverLetter("");
      const res = await API.post("/generate-cover-letter", { job_description: jobDescription });
      setCoverLetter(res.data.cover_letter);
    } catch (err) {
      const msg = err.response?.data?.detail || "Failed to generate. Did you upload a resume first?";
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Cover Letter - INDIAIN AI</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { 
              font-family: 'Inter', sans-serif; 
              line-height: 1.6; 
              color: #1a202c; 
              padding: 60px; 
              max-width: 800px; 
              margin: 0 auto; 
            }
            .date { margin-bottom: 24px; color: #718096; font-size: 14px; }
            .content { white-space: pre-wrap; font-size: 15px; }
            .footer { margin-top: 40px; border-top: 1px solid #e2e8f0; pt-4; font-size: 12px; color: #a0aec0; }
            @media print {
              body { padding: 0; }
              @page { margin: 2cm; }
            }
          </style>
        </head>
        <body>
          <div class="date">${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</div>
          <div class="content">${coverLetter}</div>
          <div class="footer">Generated by INDIAIN AI Career Platform</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
        printWindow.print();
        printWindow.close();
    }, 500);
  };

  return (
    <div className={`font-sans min-h-screen transition-colors ${isDark ? 'text-white' : 'text-slate-800'}`}>
      {/* Header */}
      <div className="mb-8">
        <div className={`inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-bold mb-3 border ${isDark ? 'bg-purple-900/30 text-purple-300 border-purple-700/50' : 'bg-purple-50 text-purple-600 border-purple-100'}`}>
          <span className="w-2 h-2 rounded-full bg-purple-500 animate-pulse" />AI Cover Letter Studio
        </div>
        <h1 className={`text-4xl md:text-5xl font-black tracking-tight ${headText}`}>Cover Letter</h1>
        <p className={`mt-2 font-medium ${subText}`}>Craft high-conversion, professional cover letters tailored to a specific role.</p>
      </div>

      {error && (
        <div className={`mb-6 p-4 rounded-2xl border text-sm font-bold ${isDark ? 'bg-red-900/20 border-red-700/30 text-red-400' : 'bg-red-50 border-red-200 text-red-600'}`}>
          {error}
        </div>
      )}

      {!coverLetter && !isLoading && (
        <div className={`backdrop-blur-xl border rounded-[2rem] p-8 ${card}`}>
          <div className="flex justify-between items-center mb-3">
             <label className={`block text-sm font-bold ${subText}`}>Target Job Requirements</label>
             {resumeText && <span className="text-xs font-bold text-emerald-500 flex items-center gap-1"><span className="w-1.5 h-1.5 rounded-full bg-emerald-500"/> Resume Loaded</span>}
          </div>
          <textarea
            value={jobDescription} onChange={e => setJobDescription(e.target.value)}
            rows={10}
            className={`w-full p-4 rounded-xl border outline-none focus:ring-2 focus:ring-purple-500/20 transition-all resize-none mb-6 ${inputClass}`}
            placeholder="Paste the job requirements to generate a perfectly tailored cover letter..."
          />
          <button onClick={generate} className="w-full py-4 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-xl font-black text-base shadow-lg hover:-translate-y-0.5 transition-all uppercase tracking-widest">
            {resumeText ? "Generate Tailored Cover Letter" : "Generate Generic Letter (Upload Resume for Better Results)"}
          </button>
        </div>
      )}

      {isLoading && (
        <div className={`backdrop-blur-xl border rounded-[2rem] p-16 flex flex-col items-center justify-center ${card}`}>
          <div className="w-14 h-14 border-4 border-purple-400 border-t-transparent rounded-full animate-spin mb-4" />
          <p className={`font-bold ${subText}`}>Synthesizing your professional narrative...</p>
        </div>
      )}

      {coverLetter && !isLoading && (
        <div className={`backdrop-blur-xl border rounded-[2rem] p-8 ${card}`}>
          <div className={`flex justify-between items-center mb-6 border-b pb-4 ${isDark ? 'border-white/10' : 'border-slate-200'}`}>
            <div>
                 <h4 className="font-bold text-emerald-500 flex items-center gap-2">
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd"/></svg>
                    Pitch Narrative Ready
                 </h4>
                 <p className="text-[10px] uppercase font-black text-slate-500 tracking-widest mt-1">AI-Optimized for Hiring Managers</p>
            </div>
            <div className="flex gap-2">
              <button onClick={() => navigator.clipboard.writeText(coverLetter)} className={`text-sm font-bold px-4 py-2.5 rounded-xl border transition-colors ${isDark ? 'bg-white/10 border-white/10 text-white hover:bg-white/20' : 'bg-slate-100 border-slate-200 hover:bg-white'}`}>Copy</button>
              <button onClick={handlePrint} className={`text-sm font-bold px-5 py-2.5 rounded-xl transition-all bg-indigo-600 text-white hover:bg-indigo-700 shadow-lg`}>Download / Print PDF</button>
              <button onClick={() => setCoverLetter("")} className={`text-sm font-bold px-4 py-2.5 rounded-xl transition-colors ${isDark ? 'bg-purple-700/40 text-purple-300 hover:bg-purple-700/60' : 'bg-purple-50 text-purple-600 hover:bg-fuchsia-100'}`}>Restart</button>
            </div>
          </div>
          <div className={`p-8 rounded-2xl border overflow-y-auto max-h-[600px] shadow-inner ${isDark ? 'bg-white/5 border-white/10' : 'bg-slate-50 border-slate-200'}`}>
            <p className={`whitespace-pre-wrap leading-loose text-sm ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>{coverLetter}</p>
          </div>
        </div>
      )}
    </div>
  );
}
